name: build-check x64 release

on:
  push:
    branches: [ stable, WIP ]
  pull_request:
    branches: [ stable, WIP ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Building project
      run: |
        msbuild DragonBurn.sln -t:Rebuild -p:Configuration=Release -p:Platform=x64

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Compiled-Binaries
        path: |
          \DragonBurn\DragonBurn\built\DragonBurn.exe