name: cmake-build-check x64 release

on:
  push:
    branches: [stable, wip_maintenance]
  pull_request:
    branches: [stable, wip_maintenance]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Configure CMake
        shell: cmd
        run: cmake -B build -A x64 -DCMAKE_CONFIGURATION_TYPES=Release -DDRAGONBURN_BUILD_KERNEL=ON -DDRAGONBURN_BUILD_MAPPER=ON -DDRAGONBURN_BUILD_USERMODE=ON

      - name: Build with CMake
        shell: cmd
        run: cmake --build build --config Release -- /m

      - name: Verify build outputs
        shell: pwsh
        run: |
          $expected = @(
            'built\DragonBurn-usermode.exe',
            'built\DragonBurn-mapper.exe',
            'built\DragonBurn-kernel.sys'
          )
          foreach ($file in $expected) {
            if (-not (Test-Path $file)) {
              Write-Warning "Build output missing: $file"
              #exit 1
            }
            else {
                Write-Host "OK: $file"
            }
          }

      - name: Archive usermode
        uses: actions/upload-artifact@v4
        with:
          name: DragonBurn-cmake-usermode-${{ github.sha }}
          path: |
           built\DragonBurn-usermode.exe
      
      - name: Archive mapper
        uses: actions/upload-artifact@v4
        with:
          name: DragonBurn-cmake-mapper-${{ github.sha }}
          path: |
           built\DragonBurn-mapper.exe
        
      - name: Archive kernel
        uses: actions/upload-artifact@v4
        with:
          name: DragonBurn-cmake-kernel-${{ github.sha }}
          path: |
           built\DragonBurn-kernel.sys
