name: release beta

on:
  push:
    branches: [stable, WIP]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Send release to discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#465173"
          username: "DragonBurn-beta"
          message: "${{ github.repository }} new commit ${{ github.event.head_commit.message }}[${{ github.sha }}] beta-release build:\n${{ steps.upload-step.outputs.artifact-url }}"
