name: release beta

on:
  push:
    branches: [stable, WIP]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Send release to discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: "DragonBurn-beta"
          discord: |
            **_DragonBurn beta release_**

            - **Commit SHA:** `${{ github.sha }}`
            - **Commit Message:** `${{ github.event.head_commit.message }}`
            - **Author:** `${{ github.actor }}`

            [View the commit on GitHub](${{ github.event.head_commit.url }})
